### ISSUE TITLE
Get rid of the open data class, no need to extend our models .

### ISSUE THREAD

**Issue by anmolvermamm** [mutualmobile/Praxis#41]
https://github.com/mutualmobile/Praxis/blob/f0829a1c41675f09a5bed79e2f0891fef7d3110f/data/src/main/java/com/mutualmobile/praxis/data/mapper/EntityMapper.kt#L11

**Comment by shubhamsinghmutualmobile** [comment]
@anmolvermamm Do we want to make this change in all the branches? Or the `baseproject` branch only?

**Comment by anmolvermamm** [comment]
> @anmolvermamm Do we want to make this change in all the branches? Or the `baseproject` branch only?

Yes! just the baseproject
